spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/users
    username: root
    password: C0dingS@int
  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  hibernate:
    ddl-auto : update

server:
  port: 8082

